In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.14.0


In [3]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['d:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'd:/ProgramData/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['d:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'd:/P

In [4]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
Z = np.zeros((10, 10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [8]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [9]:
Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [11]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [13]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
Z = np.random.random((3, 3, 3))
print(Z)

[[[0.3507504  0.23595324 0.81105871]
  [0.92935442 0.16787319 0.60474013]
  [0.26274593 0.85327539 0.75543018]]

 [[0.82046668 0.32534011 0.11993568]
  [0.5165186  0.44485712 0.81671177]
  [0.10026966 0.75164507 0.85210156]]

 [[0.45956311 0.81819249 0.24795771]
  [0.78741246 0.94761715 0.40891906]
  [0.19276187 0.39982781 0.48540311]]]


In [15]:
Z = np.random.random((10, 10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0015477489144202217 0.9913079166048616


In [16]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.40216842536705794


In [17]:
Z = np.ones((10, 10))
Z[1:-1, 1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [18]:
Z = np.ones((5, 5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [19]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [20]:
Z = np.diag(1+np.arange(4), k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [21]:
Z = np.zeros((8, 8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [22]:
print(np.unravel_index(100, (6, 7, 8)))

(1, 5, 4)


In [23]:
Z = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [24]:
Z = np.random.random((5, 5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.75540808 0.90862994 0.76061336 1.         0.29735955]
 [0.50547935 0.32144729 0.55887868 0.         0.67614442]
 [0.9536987  0.37544106 0.49053965 0.07780672 0.14962368]
 [0.75125541 0.75379215 0.54319396 0.89768246 0.57683993]
 [0.46544127 0.17330309 0.53329734 0.55737829 0.33146005]]


In [25]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [26]:
Z = np.dot(np.ones((5, 3)), np.ones((3, 2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [27]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [28]:
from numpy import *
print(sum(range(5), -1))
print(sum(range(5), -1))

9
10


In [29]:
from numpy import *
print(sum(range(5), -1))
print(sum(range(5), -1))

10
10


In [30]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


d:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
d:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [31]:
Z = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[ 5.  9. -1.  2. -2.  6. -5.  4. -6. -1.]


In [32]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
print(np.intersect1d(Z1, Z2))

[0 2 3 4]


In [33]:
np.sqrt(-1) == np.emath.sqrt(-1)


d:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [34]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Yesterday is " + str(yesterday))
print("Today is " + str(today))
print("Tomorrow is " + str(tomorrow))

Yesterday is 2019-06-22
Today is 2019-06-23
Tomorrow is 2019-06-24


In [35]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [36]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A, B, out=B)

array([3., 3., 3.])

In [37]:
Z = np.random.uniform(0, 10, 10)
print(Z - Z % 1)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

[8. 1. 5. 0. 5. 3. 7. 0. 6. 4.]
[8. 1. 5. 0. 5. 3. 7. 0. 6. 4.]
[8. 1. 5. 0. 5. 3. 7. 0. 6. 4.]
[8 1 5 0 5 3 7 0 6 4]
[8. 1. 5. 0. 5. 3. 7. 0. 6. 4.]


In [38]:
Z = np.zeros((5, 5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [39]:
def generate():
    for x in range(10):
        yield x


Z = np.fromiter(generate(), dtype=float, count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [40]:
Z = np.linspace(0, 1, 11, endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [41]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.29331643 0.36146618 0.39707633 0.6595027  0.68158615 0.82298809
 0.83559552 0.86595305 0.86753754 0.99299522]


In [42]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [44]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
equal = np.allclose(A, B)
print(equal)

False


In [45]:
equal = np.array_equal(A, B)
print(equal)

False


In [46]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.63065166 0.97170789 0.91885777 1.14813757 0.89100848 0.23065024
 1.1152222  0.92818239 0.21943334 1.32428406]
[0.80224092 1.08293822 0.22406469 0.82459062 0.07840596 1.31739303
 0.93411068 1.16606931 0.71100106 0.71832191]


In [47]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.60335265 0.56496053 0.20861218 0.79338045 0.8010072  0.71968112
 0.         0.7393958  0.11590391 0.31400765]


In [48]:
Z = np.zeros((5, 5), [('x', float), ('y', float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 5),
                             np.linspace(0, 1, 5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [49]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [50]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [51]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16, 16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [52]:
Z = np.arange(100)
v = np.random.uniform(0, 100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

71


In [53]:
Z = np.zeros(10, [('position', [('x', float, 1),
                                ('y', float, 1)]),
                  ('color',    [('r', float, 1),
                                ('g', float, 1),
                                ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [54]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print (D)

[[0.         0.29367786 1.09674295 0.86295623 0.40216326 0.62139738
  0.67038155 0.19510837 0.71758257 0.46096231]
 [0.29367786 0.         0.96120559 0.62679105 0.21583959 0.62276147
  0.60533628 0.182282   0.44566094 0.59273142]
 [1.09674295 0.96120559 0.         0.48555259 0.7473085  0.56362455
  0.4474485  0.91331189 0.69384189 0.84237715]
 [0.86295623 0.62679105 0.48555259 0.         0.46098841 0.62555262
  0.48870745 0.66981138 0.22959921 0.83558566]
 [0.40216326 0.21583959 0.7473085  0.46098841 0.         0.44167641
  0.39893254 0.20902274 0.34249694 0.49555572]
 [0.62139738 0.62276147 0.56362455 0.62555262 0.44167641 0.
  0.14416804 0.48622648 0.6683856  0.27878562]
 [0.67038155 0.60533628 0.4474485  0.48870745 0.39893254 0.14416804
  0.         0.5047624  0.55861821 0.40752884]
 [0.19510837 0.182282   0.91331189 0.66981138 0.20902274 0.48622648
  0.5047624  0.         0.53859124 0.41383138]
 [0.71758257 0.44566094 0.69384189 0.22959921 0.34249694 0.6683856
  0.55861821 0.538591

In [55]:
import scipy
import scipy.spatial
D = scipy.spatial.distance.cdist(Z, Z)
print(D)

[[0.         0.29367786 1.09674295 0.86295623 0.40216326 0.62139738
  0.67038155 0.19510837 0.71758257 0.46096231]
 [0.29367786 0.         0.96120559 0.62679105 0.21583959 0.62276147
  0.60533628 0.182282   0.44566094 0.59273142]
 [1.09674295 0.96120559 0.         0.48555259 0.7473085  0.56362455
  0.4474485  0.91331189 0.69384189 0.84237715]
 [0.86295623 0.62679105 0.48555259 0.         0.46098841 0.62555262
  0.48870745 0.66981138 0.22959921 0.83558566]
 [0.40216326 0.21583959 0.7473085  0.46098841 0.         0.44167641
  0.39893254 0.20902274 0.34249694 0.49555572]
 [0.62139738 0.62276147 0.56362455 0.62555262 0.44167641 0.
  0.14416804 0.48622648 0.6683856  0.27878562]
 [0.67038155 0.60533628 0.4474485  0.48870745 0.39893254 0.14416804
  0.         0.5047624  0.55861821 0.40752884]
 [0.19510837 0.182282   0.91331189 0.66981138 0.20902274 0.48622648
  0.5047624  0.         0.53859124 0.41383138]
 [0.71758257 0.44566094 0.69384189 0.22959921 0.34249694 0.6683856
  0.55861821 0.538591

In [56]:
# 如何将32位的浮点数(float)转换为对应的整数(integer)?
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [57]:
# 对于numpy数组，enumerate的等价操作是什么？
Z = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [58]:
# 生成一个通用的二维Gaussian-like数组
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D-mu)**2 / (2.0 * sigma**2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [59]:
# 对一个二维数组，如何在其内部随机放置p个元素?
n = 10
p = 3
Z = np.zeros((n, n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)
print(Z)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


In [60]:
# 减去一个矩阵中的每一行的平均值
X = np.random.rand(5, 10)
# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print(Y)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[ 0.19906557 -0.14944253  0.18104159 -0.04570336 -0.2471907   0.38983394
  -0.26450782 -0.18200239 -0.09504611  0.21395181]
 [-0.25954979 -0.34962591  0.00557056  0.32828124  0.47132607  0.07480513
  -0.19124122 -0.38548303 -0.12991252  0.43582948]
 [ 0.43391024  0.18725765  0.341497   -0.02808949 -0.48126976 -0.19629034
   0.14602829 -0.13513367 -0.48327403  0.2153641 ]
 [ 0.17136333  0.0703458   0.01903955 -0.55406336  0.29037238 -0.52511117
  -0.09786004  0.2851932   0.28516586  0.05555445]
 [-0.24143078  0.35812275  0.32063046 -0.39010988 -0.43769167 -0.07071897
   0.40671651 -0.15745599  0.37983323 -0.16789565]]
[[ 0.19906557 -0.14944253  0.18104159 -0.04570336 -0.2471907   0.38983394
  -0.26450782 -0.18200239 -0.09504611  0.21395181]
 [-0.25954979 -0.34962591  0.00557056  0.32828124  0.47132607  0.07480513
  -0.19124122 -0.38548303 -0.12991252  0.43582948]
 [ 0.43391024  0.18725765  0.341497   -0.02808949 -0.48126976 -0.19629034
   0.14602829 -0.13513367 -0.48327403  0.2153641 ]

In [61]:
# 如何通过第n列对一个数组进行排序?
Z = np.random.randint(0, 10, (3, 3))
print(Z)
print(Z[Z[:, 1].argsort()])

[[7 0 8]
 [0 7 4]
 [9 5 6]]
[[7 0 8]
 [9 5 6]
 [0 7 4]]


In [62]:
# 如何检查一个二维数组是否有空列？
Z = np.random.randint(0, 3, (3, 10))
print((~Z.any(axis=0)).any())

False


In [63]:
# 从数组中的给定值中找出最近的值
Z = np.random.uniform(0, 1, 10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.6138448932863242


In [64]:
# 如何用迭代器(iterator)计算两个分别具有形状(1,3)和(3,1)的数组?
A = np.arange(3).reshape(3, 1)
B = np.arange(3).reshape(1, 3)
it = np.nditer([A, B, None])
for x, y, z in it:
    z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [65]:
# 创建一个具有name属性的数组类
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.info = getattr(obj, 'name', "no name")


Z = NamedArray(np.arange(10), "range_10")
print(Z.name)

range_10


In [66]:
# 考虑一个给定的向量，如何对由第二个向量索引的每个元素加1(小心重复的索引)?
Z = np.ones(10)
I = np.random.randint(0, len(Z), 20)
Z += np.bincount(I, minlength=len(Z))
print(Z)
# 方法2
np.add.at(Z, I, 1)
print(Z)

[4. 2. 4. 2. 2. 4. 4. 3. 2. 3.]
[7. 3. 7. 3. 3. 7. 7. 5. 3. 5.]


In [67]:
# 根据索引列表(I)，如何将向量(X)的元素累加到数组(F)?
X = [1, 2, 3, 4, 5, 6]
I = [1, 3, 9, 3, 4, 1]
F = np.bincount(I, X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [69]:
# 考虑一个(dtype=ubyte) 的 (w,h,3)图像，计算其唯一颜色的数量
w, h = 16, 16
I = np.random.randint(0, 2, (h, w, 3)).astype(np.ubyte)
# Note that we should compute 256*256 first.
# Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[..., 0]*(256*256) + I[..., 1]*256 + I[..., 2]
n = len(np.unique(F))
print(n)

8


In [70]:
# 考虑一个四维数组，如何一次性计算出最后两个轴(axis)的和？
A = np.random.randint(0, 10, (3, 4, 3, 4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2, -1))
print(sum)
# 方法2
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[58 51 63 38]
 [61 42 65 55]
 [43 45 69 63]]
[[58 51 63 38]
 [61 42 65 55]
 [43 45 69 63]]


In [71]:
# 考虑一个一维向量D，如何使用相同大小的向量S来计算D子集的均值？
import pandas as pd
D = np.random.uniform(0, 1, 100)
S = np.random.randint(0, 10, 100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
# 方法2
print(pd.Series(D).groupby(S).mean())

[0.55780378 0.61757349 0.53757692 0.40847826 0.5131122  0.64228042
 0.41470186 0.31811182 0.54509712 0.54123742]
0    0.557804
1    0.617573
2    0.537577
3    0.408478
4    0.513112
5    0.642280
6    0.414702
7    0.318112
8    0.545097
9    0.541237
dtype: float64


In [72]:
# 如何获得点积 dot prodcut的对角线?
A = np.random.uniform(0, 1, (5, 5))
B = np.random.uniform(0, 1, (5, 5))
# slow version
np.diag(np.dot(A, B))
# 方法2
# Fast version
np.sum(A * B.T, axis=1)
# 方法3
# Faster version
np.einsum("ij,ji->i", A, B)

array([0.93007495, 0.79717508, 1.976473  , 1.15415942, 1.02260486])

In [73]:
#  考虑一个向量[1,2,3,4,5],如何建立一个新的向量，在这个新向量中每个值之间有3个连续的零？
Z = np.array([1, 2, 3, 4, 5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [74]:
# 考虑一个维度(5,5,3)的数组，如何将其与一个(5,5)的数组相乘？
A = np.ones((5, 5, 3))
B = 2*np.ones((5, 5))
print(A * B[:, :, None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [75]:
# 如何对一个数组中任意两行做交换?
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [76]:
# 考虑一个可以描述10个三角形的triplets，找到可以分割全部三角形的line segment
faces = np.random.randint(0, 100, (10, 3))
F = np.roll(faces.repeat(2, axis=1), -1, axis=1)
F = F.reshape(len(F)*3, 2)
F = np.sort(F, axis=1)
G = F.view(dtype=[('p0', F.dtype), ('p1', F.dtype)])
G = np.unique(G)
print(G)

[( 9, 74) ( 9, 75) (13, 59) (13, 83) (20, 35) (20, 57) (22, 65) (22, 74)
 (23, 27) (23, 42) (23, 73) (23, 98) (24, 59) (24, 82) (27, 73) (33, 83)
 (33, 88) (35, 48) (35, 57) (35, 87) (42, 50) (42, 51) (42, 98) (48, 87)
 (50, 51) (59, 82) (59, 83) (65, 74) (74, 75) (83, 88)]


In [77]:
# 给定一个二进制的数组C，如何产生一个数组A满足np.bincount(A)==C
C = np.bincount([1, 1, 2, 3, 4, 4, 6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [78]:
# 如何通过滑动窗口计算一个数组的平均数?
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n


Z = np.arange(20)

print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [80]:
# 考虑一维数组Z，构建一个二维数组，其第一行为（Z [0]，Z [1]，Z [2]），每个后续行移1（最后一行应为（Z [-3]，Z[-2]，Z[-1]）
from numpy.lib import stride_tricks


def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)


Z = rolling(np.arange(10), 3)

print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [81]:
# 如何对布尔值取反，或者原位(in-place)改变浮点数的符号(sign)？
Z = np.random.randint(0, 2, 100)
np.logical_not(Z, out=Z)
Z = np.random.uniform(-1.0, 1.0, 100)
np.negative(Z, out=Z)

array([ 0.8473283 ,  0.26955354, -0.42271503,  0.10152097, -0.56882721,
        0.0973279 ,  0.35027506,  0.72173517,  0.53620117, -0.04990215,
       -0.09453702, -0.45677998, -0.50723142, -0.62920881,  0.95210605,
       -0.03568002,  0.4441367 , -0.6359035 , -0.61594122, -0.75452694,
        0.74773865,  0.50426538, -0.95711447,  0.61062609,  0.643498  ,
        0.44470877, -0.82159666,  0.68192448, -0.69854668, -0.65540398,
        0.78128746,  0.31056307, -0.52241942, -0.37280047,  0.04519586,
       -0.0764064 , -0.50631083, -0.32750162, -0.04057664, -0.77927034,
       -0.43670249,  0.15981934,  0.47923283, -0.05506581, -0.32396389,
        0.3247291 , -0.34508323, -0.03954591, -0.96559362, -0.96996265,
       -0.61238068,  0.79740691,  0.0699624 , -0.41005188, -0.94053026,
       -0.16923676,  0.54388818, -0.74674307, -0.26672748, -0.98370216,
        0.71510236,  0.99922317, -0.31819363,  0.85963317, -0.58674141,
        0.93503762,  0.00958248,  0.83752683,  0.86780035, -0.07

In [82]:
# 考虑两组点集P0和P1去描述一组线(二维)和一个点p,如何计算点p到每一条线 i (P0[i],P1[i])的距离？
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:, 0]-p[..., 0])*T[:, 0] + (P0[:, 1]-p[..., 1])*T[:, 1]) / L
    U = U.reshape(len(U), 1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))


P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (1, 2))

print(distance(P0, P1, p))

[ 0.65181953  8.86601338 12.40423695  2.53911388 11.11766643 15.67078407
  7.6809442   8.90094459 11.57185365  4.76591441]


In [83]:
# 考虑两组点集P0和P1去描述一组线(二维)和一组点集P，如何计算每一个点 j(P[j]) 到每一条线 i (P0[i],P1[i])的距离？
P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (10, 2))
print(np.array([distance(P0, P1, p_i) for p_i in p]))

[[1.24056253e+01 4.17661119e-01 2.66605808e+00 6.53797409e+00
  1.26977224e+01 9.92630049e+00 5.76418591e+00 9.08222490e+00
  1.45197788e+01 2.38215848e+00]
 [5.77186845e+00 7.13848539e+00 1.06363331e+01 6.70370701e+00
  1.09615032e+01 9.40243323e-01 9.50356917e+00 1.04858385e+01
  3.56365403e+00 8.23073593e+00]
 [7.81932363e+00 8.08222411e+00 1.14918286e+01 8.61089479e+00
  1.29805288e+01 2.80549912e+00 1.10621649e+01 1.22931674e+01
  5.02677891e+00 8.31843041e+00]
 [6.44149171e-01 5.30801826e+00 1.64828047e+00 4.94542742e+00
  3.38360208e-01 2.27401628e+00 3.23840657e+00 1.66782176e+00
  4.53568217e+00 1.78637861e+00]
 [3.91360304e+00 1.01046430e+01 1.37287600e+01 7.25797423e+00
  1.08597646e+01 1.81247596e+00 1.12545260e+01 1.14600457e+01
  2.88723482e-03 1.20758216e+01]
 [2.32758603e+00 4.05977349e+00 7.68805257e+00 2.60398049e+00
  6.88993663e+00 1.78413209e+00 5.64686853e+00 6.42564285e+00
  1.97557009e+00 6.55230257e+00]
 [1.91812039e+00 6.32025211e+00 9.99576641e+00 3.68672031e

In [84]:
# 考虑一个任意数组，编写一个函数，提取一个固定形状的子部分，并以给定元素为中心(必要时用填充值填充)
Z = np.random.randint(0, 10, (10, 10))
shape = (5, 5)
fill = 0
position = (1, 1)

R = np.ones(shape, dtype=Z.dtype)*fill
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop = (P+Rs//2)+Rs % 2

R_start = (R_start - np.minimum(Z_start, 0)).tolist()
Z_start = (np.maximum(Z_start, 0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs, 0))).tolist()
Z_stop = (np.minimum(Z_stop, Zs)).tolist()

r = [slice(start, stop) for start, stop in zip(R_start, R_stop)]
z = [slice(start, stop) for start, stop in zip(Z_start, Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[9 2 0 6 3 1 7 6 6 8]
 [5 5 8 6 7 2 9 5 3 8]
 [4 8 6 9 2 8 9 2 2 8]
 [9 6 6 2 3 3 0 4 8 3]
 [1 8 3 9 0 2 1 5 9 4]
 [7 9 2 2 4 7 7 9 7 8]
 [8 6 7 3 0 8 2 7 2 7]
 [0 2 1 2 7 5 1 9 6 4]
 [3 1 5 5 6 9 3 9 0 4]
 [8 8 2 3 1 5 9 1 0 5]]
[[0 0 0 0 0]
 [0 9 2 0 6]
 [0 5 5 8 6]
 [0 4 8 6 9]
 [0 9 6 6 2]]


In [85]:
# 考虑一个数组Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14],如何生成一个数组R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ...,[11,12,13,14]]?
Z = np.arange(1, 15, dtype=np.uint32)
R = stride_tricks.as_strided(Z, (11, 4), (4, 4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [86]:
# 计算一个矩阵的秩
Z = np.random.uniform(0, 1, (10, 10))
U, S, V = np.linalg.svd(Z)  # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


In [87]:
# 如何找到一个数组中出现频率最高的值？
Z = np.random.randint(0, 10, 50)
print(np.bincount(Z).argmax())

4


In [89]:
# 从一个10x10的矩阵中提取出连续的3x3区块
Z = np.random.randint(0, 5, (10, 10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(
    Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 2 0]
   [1 3 4]
   [1 2 1]]

  [[2 0 1]
   [3 4 1]
   [2 1 0]]

  [[0 1 0]
   [4 1 4]
   [1 0 2]]

  [[1 0 3]
   [1 4 4]
   [0 2 4]]

  [[0 3 0]
   [4 4 0]
   [2 4 0]]

  [[3 0 2]
   [4 0 1]
   [4 0 1]]

  [[0 2 1]
   [0 1 4]
   [0 1 2]]

  [[2 1 0]
   [1 4 1]
   [1 2 3]]]


 [[[1 3 4]
   [1 2 1]
   [3 4 0]]

  [[3 4 1]
   [2 1 0]
   [4 0 2]]

  [[4 1 4]
   [1 0 2]
   [0 2 4]]

  [[1 4 4]
   [0 2 4]
   [2 4 1]]

  [[4 4 0]
   [2 4 0]
   [4 1 0]]

  [[4 0 1]
   [4 0 1]
   [1 0 4]]

  [[0 1 4]
   [0 1 2]
   [0 4 2]]

  [[1 4 1]
   [1 2 3]
   [4 2 2]]]


 [[[1 2 1]
   [3 4 0]
   [4 2 1]]

  [[2 1 0]
   [4 0 2]
   [2 1 1]]

  [[1 0 2]
   [0 2 4]
   [1 1 1]]

  [[0 2 4]
   [2 4 1]
   [1 1 3]]

  [[2 4 0]
   [4 1 0]
   [1 3 1]]

  [[4 0 1]
   [1 0 4]
   [3 1 2]]

  [[0 1 2]
   [0 4 2]
   [1 2 4]]

  [[1 2 3]
   [4 2 2]
   [2 4 4]]]


 [[[3 4 0]
   [4 2 1]
   [2 0 0]]

  [[4 0 2]
   [2 1 1]
   [0 0 4]]

  [[0 2 4]
   [1 1 1]
   [0 4 3]]

  [[2 4 1]
   [1 1 3]
   [4 3 2]]

  [[4 1 0]
   

In [90]:
# 创建一个满足 Z[i,j] == Z[j,i]的子类
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super(Symetric, self).__setitem__((i, j), value)
        super(Symetric, self).__setitem__((j, i), value)


def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)


S = symetric(np.random.randint(0, 10, (5, 5)))
S[2, 3] = 42
print(S)

[[ 7  7 18 15 14]
 [ 7  0 16 12 15]
 [18 16  2 42 12]
 [15 12 42  3  3]
 [14 15 12  3  4]]


In [91]:
# 考虑p个 nxn 矩阵和一组形状为(n,1)的向量，如何直接计算p个矩阵的乘积(n,1)？
p, n = 10, 20
M = np.ones((p, n, n))
V = np.ones((p, n, 1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)
# It works, because:
# M is (p, n, n)
# V is (p, n, 1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a(n, 1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [92]:
#  对于一个16x16的数组，如何得到一个区域(block-sum)的和(区域大小为4x4)?
Z = np.ones((16, 16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                    np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [93]:
# 如何利用numpy数组实现Game of Life?
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2, 0:-2] + Z[0:-2, 1:-1] + Z[0:-2, 2:] +
         Z[1:-1, 0:-2] + Z[1:-1, 2:] +
         Z[2:, 0:-2] + Z[2:, 1:-1] + Z[2:, 2:])

    # Apply rules
    birth = (N == 3) & (Z[1:-1, 1:-1] == 0)
    survive = ((N == 2) | (N == 3)) & (Z[1:-1, 1:-1] == 1)
    Z[...] = 0
    Z[1:-1, 1:-1][birth | survive] = 1
    return Z


Z = np.random.randint(0, 2, (50, 50))
for i in range(100):
    Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 0 0 0 0 1 1 0 0 0 0 0 1 0 0 1 1 0 0 0 1 0 0 1 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 1 0 1 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0

In [94]:
# 如何找到一个数组的第n个最大值?
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
# Slow
print(Z[np.argsort(Z)[-n:]])
# 方法2
# Fast
print(Z[np.argpartition(-Z, n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


In [95]:
# 给定任意个数向量，创建笛卡尔积(每一个元素的每一种组合)
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix


print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [96]:
# 如何从一个正常数组创建记录数组(record array)?
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats='S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [97]:
# 考虑一个大向量Z, 用三种不同的方法计算它的立方
x = np.random.rand()
np.power(x, 3)

0.22532927915516068

In [98]:
# 考虑两个形状分别为(8,3) 和(2,2)的数组A和B. 如何在数组A中找到满足包含B中元素的行？(不考虑B中每行元素顺序)？
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3, 1)).all(1))[0]
print(rows)

[0 1 2 3 5 6 7]


In [99]:
# 考虑一个10x3的矩阵，分解出有不全相同值的行 (如 [2,2,3])
Z = np.random.randint(0, 5, (10, 3))
print(Z)

# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:, 1:] == Z[:, :-1], axis=1)
U = Z[~E]
print(U)
# 方法2
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1), :]
print(U)

[[4 3 3]
 [4 1 1]
 [0 4 3]
 [0 4 1]
 [4 1 0]
 [0 0 1]
 [3 4 0]
 [3 4 2]
 [3 0 4]
 [2 4 2]]
[[4 3 3]
 [4 1 1]
 [0 4 3]
 [0 4 1]
 [4 1 0]
 [0 0 1]
 [3 4 0]
 [3 4 2]
 [3 0 4]
 [2 4 2]]
[[4 3 3]
 [4 1 1]
 [0 4 3]
 [0 4 1]
 [4 1 0]
 [0 0 1]
 [3 4 0]
 [3 4 2]
 [3 0 4]
 [2 4 2]]


In [101]:
# 将一个整数向量转换为matrix binary的表现形式
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1, 1) & (2**np.arange(8))) != 0).astype(int)
print(B[:, ::-1])
# 方法2
# print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [102]:
#  给定一个二维数组，如何提取出唯一的(unique)行?
Z = np.random.randint(0, 2, (6, 3))
T = np.ascontiguousarray(Z).view(
    np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 1]]


In [103]:
# 考虑两个向量A和B，写出用einsum等式对应的inner, outer, sum, mul函数
A = np.random.uniform(0, 1, 10)
B = np.random.uniform(0, 1, 10)
print('sum')
print(np.einsum('i->', A))  # np.sum(A)
print('A * B')
print(np.einsum('i,i->i', A, B))  # A * B
print('inner')
print(np.einsum('i,i', A, B))    # np.inner(A, B)
print('outer')
print(np.einsum('i,j->ij', A, B))    # np.outer(A, B)

sum
4.356033318222802
A * B
[0.40858666 0.14162842 0.1916743  0.24573932 0.21212022 0.06040435
 0.0760701  0.02682496 0.34254408 0.07697234]
inner
1.782564746578459
outer
[[0.40858666 0.23649605 0.34338632 0.2647845  0.23527953 0.24327084
  0.10750832 0.11881713 0.26735172 0.10781387]
 [0.2446869  0.14162842 0.20564091 0.15856929 0.1408999  0.14568558
  0.06438261 0.07115502 0.1601067  0.0645656 ]
 [0.22806838 0.13200938 0.1916743  0.14779967 0.13133033 0.13579099
  0.06000991 0.06632235 0.14923266 0.06018047]
 [0.37919821 0.21948557 0.31868753 0.24573932 0.21835656 0.22577307
  0.09977555 0.11027095 0.24812188 0.10005913]
 [0.36836819 0.213217   0.30958572 0.23872093 0.21212022 0.21932492
  0.09692593 0.10712158 0.24103544 0.09720141]
 [0.10145241 0.05872216 0.08526311 0.06574621 0.0584201  0.06040435
  0.0266944  0.02950239 0.06638365 0.02677027]
 [0.28910535 0.16733848 0.24297127 0.18735466 0.16647771 0.17213215
  0.0760701  0.08407192 0.18917116 0.07628631]
 [0.09224529 0.05339295 

In [105]:
# 考虑一个由两个向量描述的路径(X,Y)，如何用等距样例(equidistant samples)对其进行采样(sample)?
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5  # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200)  # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [106]:
# 给定一个整数n和一个2D数组X，从X中选择可以解释为从n度多项式分布中抽取的行，即只包含整数且总和为n的行
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [107]:
# 对于一个一维数组X，计算它boostrapped之后的95%置信区间的平均值。
X = np.random.randn(100)  # random 1D array
N = 1000  # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.16969708  0.17912874]
