In [1]:
import pandas as pd

In [3]:
obj = pd.Series([4, 7, -5, 3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2['a'] 

-5

In [11]:
obj2['d'] = 6

In [12]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [14]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [15]:
obj2[obj2 > 0] 

d    6
b    7
c    3
dtype: int64

In [16]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [17]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [18]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [19]:
'b' in obj2

True

In [20]:
'e' in obj2

False

In [21]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [22]:
obj3 = pd.Series(sdata)

In [23]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [24]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [25]:
obj4 = pd.Series(sdata, index=states)

In [26]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [27]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [28]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [29]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [32]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [33]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [34]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [35]:
obj4.name = 'population'

In [36]:
obj4.index.name = 'state'

In [37]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [38]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [39]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [40]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [41]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],         'year': [2000, 2001, 2002, 2001, 2002, 2003],         'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [43]:
frame = pd.DataFrame(data)

In [44]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002
5  3.2  Nevada  2003

In [45]:
frame.head()

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [46]:
pd.DataFrame(data, columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [48]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five', 'six'])


In [49]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [50]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [51]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [52]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [53]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [54]:
frame2['debt'] = 16.5

In [55]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [56]:
frame2['debt'] = np.arange(6.)

In [57]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [58]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [59]:
frame2['debt'] = val 

In [60]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [61]:
frame2['eastern'] = frame2.state == 'Ohio'

In [62]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [63]:
del frame2['eastern']

In [64]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [65]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [66]:
frame3 = pd.DataFrame(pop)

In [67]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [68]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [69]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [70]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [71]:
pdata = {'Ohio': frame3['Ohio'][:-1],'Nevada': frame3['Nevada'][:2]}

In [72]:
pd.DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [73]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [74]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [75]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [76]:
frame2.values 

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [77]:
obj = pd.Series(range(3), index=['a', 'b', 'c']) 

In [78]:
index = obj.index

In [79]:
index

Index(['a', 'b', 'c'], dtype='object')

In [80]:
index[1:]

Index(['b', 'c'], dtype='object')

In [81]:
labels = pd.Index(np.arange(3))

In [82]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [83]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [84]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [85]:
obj2.index is labels 

True

In [86]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [87]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [88]:
'Ohio' in frame3.columns 

True

In [89]:
2003 in frame3.index

False

In [90]:
dup_labels = pd.Index(['foo','foo','bar','bar'])

In [91]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [92]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [93]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [94]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e']) 

In [95]:
obj2 

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [96]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [97]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [98]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [99]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),index=['a','c','d'],columns=['Ohio','Texas','California'])

In [100]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [101]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [102]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [103]:
states = ['Texas', 'Utah', 'California']

In [104]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [105]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [106]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [107]:
new_obj = obj.drop('c')

In [108]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [109]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [112]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])

In [111]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [113]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [114]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [115]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [116]:
obj.drop('c', inplace=True)

In [117]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [118]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [119]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [120]:
obj['b']

1.0

In [121]:
obj[1]

1.0

In [122]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [123]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [124]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [125]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [126]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [127]:
obj['b':'c'] = 5

In [128]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),index=['Ohio', 'Colorado', 'Utah', 'New York'],columns=['one', 'two', 'three', 'four'])

In [129]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [130]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [131]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [132]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [133]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [134]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [135]:
data[data < 5] = 0

In [136]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [137]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [138]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [139]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [140]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [141]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [142]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [144]:
ser = pd.Series(np.arange(3.))

In [145]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [146]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [147]:
ser2[-1]

2.0

In [148]:
ser[:1]

0    0.0
dtype: float64

In [149]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [150]:
ser.iloc[:1]

0    0.0
dtype: float64

In [151]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [152]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [153]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [154]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [155]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [156]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),  index=['Ohio', 'Texas', 'Colorado'])

In [157]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [158]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [159]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [160]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [161]:
df1*2

b     c     d
Ohio       0.0   2.0   4.0
Texas      6.0   8.0  10.0
Colorado  12.0  14.0  16.0

In [162]:
df1 = pd.DataFrame({'A': [1, 2]})

In [163]:
df2 = pd.DataFrame({'B': [3, 4]})

In [165]:
df1

A
0  1
1  2

In [166]:
df2

B
0  3
1  4

In [167]:
df1-df2

A   B
0 NaN NaN
1 NaN NaN

In [168]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),  columns=list('abcd'))

In [170]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),  columns=list('abcde'))

In [171]:
df2.loc[1, 'b'] = np.nan

In [172]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [173]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [174]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [175]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [176]:
1 / df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [177]:
df1.rdiv(1)

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [178]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [179]:
arr = np.arange(12.).reshape((3, 4))

In [180]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [181]:
arr[0]

array([0., 1., 2., 3.])

In [182]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [183]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [184]:
series = frame.iloc[0]

In [185]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [186]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [187]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [188]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [189]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [190]:
series3 = frame['d']

In [191]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [192]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [193]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [194]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon']) 

In [195]:
frame

b         d         e
Utah    0.156512  0.619773 -1.692194
Ohio    0.372499 -0.844338  0.271278
Texas   0.840630 -0.496583  0.755185
Oregon -0.336704  0.250219 -0.171880

In [196]:
np.abs(frame)

b         d         e
Utah    0.156512  0.619773  1.692194
Ohio    0.372499  0.844338  0.271278
Texas   0.840630  0.496583  0.755185
Oregon  0.336704  0.250219  0.171880

In [197]:
f = lambda x: x.max() - x.min()

In [198]:
frame.apply(f)

b    1.177334
d    1.464112
e    2.447379
dtype: float64

In [199]:
frame.apply(f, axis='columns')

Utah      2.311967
Ohio      1.216838
Texas     1.337213
Oregon    0.586923
dtype: float64

In [202]:
def f(x): 
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [201]:
frame.apply(f)

b         d         e
min -0.336704 -0.844338 -1.692194
max  0.840630  0.619773  0.755185

In [203]:
format = lambda x: '%.2f' % x

In [204]:
frame.applymap(format)

b      d      e
Utah     0.16   0.62  -1.69
Ohio     0.37  -0.84   0.27
Texas    0.84  -0.50   0.76
Oregon  -0.34   0.25  -0.17

In [205]:
frame['e'].map(format)

Utah      -1.69
Ohio       0.27
Texas      0.76
Oregon    -0.17
Name: e, dtype: object

In [206]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [207]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [208]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),                    
                     index=['three', 'one'], 
                     columns=['d', 'a', 'b', 'c']) 

In [209]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [210]:
 frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [211]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [212]:
obj = pd.Series([4, 7, -3, 2])

In [213]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [214]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [215]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [216]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [217]:
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [218]:
frame.sort_values(by='b')

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [219]:
frame.sort_values(by=['a', 'b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [220]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4]) 

In [221]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [222]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [223]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [225]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],  'c': [-2, 5, 8, -2.5]})

In [226]:
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [227]:
frame.rank(axis='columns')

a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

In [228]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [229]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [230]:
obj.index.is_unique 

False

In [231]:
obj['a'] 

a    0
a    1
dtype: int64

In [232]:
obj['c'] 

4

In [233]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [234]:
df

0         1         2
a -1.234796  0.118199  0.683358
a -0.005788 -0.320795 -0.742958
b  0.845050  0.205204 -0.113285
b  1.058849 -0.327401  1.377387

In [235]:
df.loc['b'] 

0         1         2
b  0.845050  0.205204 -0.113285
b  1.058849 -0.327401  1.377387

In [237]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],  [np.nan, np.nan], [0.75, -1.3]],index=['a', 'b', 'c', 'd'], columns=['one', 'two'])

In [238]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [239]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [240]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [241]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [242]:
df.idxmax()

one    b
two    d
dtype: object

In [243]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [244]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [245]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [246]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [250]:
import pandas_datareader.data as web

In [251]:
all_data = {ticker: web.get_data_yahoo(ticker)             for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [252]:
price = pd.DataFrame({ticker: data['Adj Close']                      for ticker, data in all_data.items()})

In [253]:
volume = pd.DataFrame({ticker: data['Volume']for ticker, data in all_data.items()})

In [254]:
returns = price.pct_change()

In [255]:
returns.tail()

AAPL      GOOG       IBM      MSFT
Date                                              
2019-06-19 -0.002923 -0.001151  0.005133  0.003921
2019-06-20  0.008036  0.008246  0.012912  0.009286
2019-06-21 -0.003409  0.009411  0.002521  0.000146
2019-06-24 -0.001006 -0.005669  0.001078  0.005914
2019-06-25 -0.015158 -0.026149 -0.007104 -0.031572

In [256]:
returns['MSFT'].corr(returns['IBM'])

0.4870579333972048

In [257]:
returns['MSFT'].cov(returns['IBM'])

8.680743356886965e-05

In [258]:
returns.MSFT.corr(returns.IBM)

0.4870579333972048

In [259]:
returns.corr()

AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.461116  0.379376  0.453093
GOOG  0.461116  1.000000  0.403112  0.538028
IBM   0.379376  0.403112  1.000000  0.487058
MSFT  0.453093  0.538028  0.487058  1.000000

In [260]:
returns.cov()

AAPL      GOOG       IBM      MSFT
AAPL  0.000266  0.000116  0.000076  0.000107
GOOG  0.000116  0.000239  0.000077  0.000120
IBM   0.000076  0.000077  0.000152  0.000087
MSFT  0.000107  0.000120  0.000087  0.000209

In [261]:
returns.corrwith(returns.IBM)

AAPL    0.379376
GOOG    0.403112
IBM     1.000000
MSFT    0.487058
dtype: float64

In [262]:
returns.corrwith(volume)

AAPL   -0.061945
GOOG   -0.020494
IBM    -0.156114
MSFT   -0.090037
dtype: float64

In [263]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [264]:
uniques = obj.unique()

In [265]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [266]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [267]:
pd.value_counts(obj.values, sort=False)

b    2
c    3
d    1
a    3
dtype: int64

In [268]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [269]:
mask = obj.isin(['b', 'c'])

In [270]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [271]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [272]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [273]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [274]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [275]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],'Qu2': [2, 3, 1, 2, 3],'Qu3': [1, 5, 2, 4, 4]})

In [276]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [277]:
result = data.apply(pd.value_counts).fillna(0)

In [278]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0